# Generated by Django 2.2.3 on 2019-07-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('uname', 'planTime')},
        ),
    ]
