# Generated by Django 2.2.3 on 2019-07-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='afternoonPlanName',
            field=models.CharField(max_length=128, verbose_name='下午计划'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='moringPlanName',
            field=models.CharField(max_length=128, verbose_name='上午计划'),
        ),
    ]
